routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UtamaController@welcome')->name('/');
Route::get('/profil', 'UtamaController@tentang')->name('/profil');
Route::get('/struktur', 'UtamaController@struktur')->name('/struktur');
Route::get('/faq', 'UtamaController@faq')->name('/faq');
Route::get('/blog', 'UtamaController@blog')->name('/blog');
Route::get('/blog-one/{id}', 'UtamaController@blogOne')->name('blog-one');
Route::get('/page_doc', 'UtamaController@page_doc')->name('/page_doc');
Route::get('resource/download_dokumen', ['as' => 'resource.download', 'uses' => 'SessionController@download']);

Route::get('/login', 'SessionController@form')->name('login');
Route::post('/login', 'SessionController@validasi')->name('process_login');
Route::get('/logout', 'SessionController@logout')->name('logout');
Route::get('/registration', 'SessionController@registration')->name('registration');
Route::post('/registration', 'SessionController@registrationStore', ['middleware' => 'web'])->name('process_registration');

Route::group(['prefix' => 'anggota', 'middleware' => 'AnggotaMiddleware'], function () {
    Route::get('/', 'DashboardController@dashboard_anggota')->name('anggota');
    Route::resource('profil_anggota', 'AnggotaProfilController');
    Route::resource('password_anggota', 'UpdatePassword');
    Route::resource('simpanan_anggota', 'AnggotaPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_anggota', 'AnggotaDokumenController');
    Route::get('resource/download_anggota', ['as' => 'anggota.resource.download', 'uses' => 'AnggotaDokumenController@download']);
    Route::resource('belanja_anggota', 'BelanjaAnggotaController');
});

Route::group(['prefix' => 'investor', 'middleware' => 'InvestorMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'InvestorProfilController@getOmset');

    Route::get('/', 'DashboardController@dashboard_investor')->name('investor');
    Route::resource('profil', 'InvestorProfilController');
    Route::resource('password', 'UpdatePassword');
    Route::resource('simpanan', 'InvestorPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('investasis', 'InvestorInvestasiController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_investor', 'InvestorDokumenController');
    Route::get('resource/download_investor', ['as' => 'investor.resource.download', 'uses' => 'InvestorDokumenController@download']);
    Route::resource('belanja_investor', 'BelanjaInvestorController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'AdminMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'AnggotaController@getOmset');

    Route::get('/', 'DashboardController@dashboard_admin')->name('admin');

    //route laporan unit usaha
    Route::get('/download/{jenis}/{id}', array('as' => 'download', 'uses' => 'LaporanController@download'));
    Route::get('/pdfview/{id}', array('as' => 'pdfview', 'uses' => 'LaporanController@pdfview'));
    Route::get('/iniLaporan', 'LaporanController@iniLaporan')->name('iniLaporan');

    Route::resource('role', 'RoleController', ['except' => [
    'create', 'store', 'destroy',
    ]]);

    Route::resource('user', 'UserController');

    Route::resource('anggota', 'AnggotaController');

    Route::get('anggota/simpanan/{id}', 'AdminAnggotaSimpanan@awal')->name('anggota.simpanan');
    Route::get('anggota/investasi/{id}', 'AdminAnggotaInvestasi@awal')->name('anggota.investasi');

    Route::get('/ubah/anggota/{id}/{status}', 'AnggotaController@status');

    Route::resource('jabatan', 'JabatanController');

    Route::resource('jenis_investasi', 'JenisInvestasiController');

    Route::resource('jenis_pembayaran', 'JenisPembayaranController');

    Route::resource('investasi', 'InvestasiController');
    Route::resource('omset', 'OmsetController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('resource/download', ['as' => 'admin.resource.download', 'uses' => 'DokumenController@download']);

    Route::resource('pembayaran', 'PembayaranController');

    Route::get('/ubah/pembayaran/{id}/{status}', 'PembayaranController@status');

    Route::get('/ubah/investasi/{id}/{status}', 'InvestasiController@status');

    Route::get('/ubah/pengambilan/{id}/{status}', 'PengambilanController@status');

    Route::resource('kepengurusan', 'KepengurusanController');

    Route::resource('penjualan', 'PenjualanController', ['except' => ['show', 'edit', 'destroy']]);

    Route::resource('pengambilan', 'PengambilanController');

    Route::resource('visimisi', 'VisimisiController');

    Route::resource('badanhukum', 'BadanhukumController');

    Route::resource('ketentuan', 'KetentuanController');

    Route::resource('faq', 'FaqController');

    Route::resource('berita', 'BeritaController');

    Route::resource('shu', 'ShuController');

    Route::resource('dewan', 'DewanController');
    Route::resource('belanja', 'BelanjaController');

    Route::get('data-omset','DataOmsetController@dataOmset')->name('data.omset');
    Route::get('data-anggota-tahunan','DataOmsetController@dataAnggotaTahunan')->name('data.anggota.tahunan');
    Route::get('data-keuntungan-tahunan','DataOmsetController@dataKeuntunganTahunan')->name('data.keuntungan.tahunan');

});

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/kirim-sms', function (){
//    $sms = new \App\Helpers\Zenziva();
  //  $sms->send('085652095696','test kirim zenziva sms');
//});

Route::get('/generate-barcode', function () {
    $anggota = new \App\Model\AnggotaModel();
    //use Milon\Barcode\DNS1D;
    $barcode = new \Milon\Barcode\DNS1D();
    $i = 0;
    foreach ($anggota->get() as $row) {
        ++$i;
        //echo '<img src="data:image/png;base64,' . $barcode->getBarcodePNG($row->nomor_anggota, "C128",2,33,array(1,1,1), true) . '" alt="barcode"   />';

        $barcode->setStorPath(storage_path('/app/images/barcode_anggota/'.$row->nama.'_'));
        $img = $barcode->getBarcodePNGPath($row->nomor_anggota, 'C128', 2, 33);
        //echo $barcode->getBarcodePNGPath($row->nomor_anggota, "C128",3,33,array(255,255,0), true);
        // return response($img.'<br>');
        echo $row->nomor_anggota.'<br>';
    }
});

Route::get('/ajax-chart-anggota', 'DashboardController@ajaxChartAnggota')->name('get.ajaxAnggota');
Route::get('/ajax-chart-line-omzet', 'DashboardController@ajaxLineOmzet')->name('get.ajaxLineOmzet');
Route::get('/ajax-change-toko', 'DashboardController@changeToko')->name('get.changeToko');

app/Http/Controllers/InvestasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\InvestasiModel;
use App\Model\AnggotaModel;
use App\Model\JenisInvestasiModel;
use App\Model\NotificationsModel;
use App\Model\UserModel;
use App\Http\Requests\InvestasiRequest;
use \App\Notifications\VerifikasiInvestasi;
use Intervention\Image\ImageManagerStatic as Image;
class InvestasiController extends Controller
{
    public function index(Request $request){

        //list semua investasi
        $semuaInvestasi= InvestasiModel::Cari($request)->orderBy('id', 'DESC')->paginate(10);

        //hapus notifikasi new investasi di navbr
        $new_inves= NotificationsModel::where('type','=','App\Notifications\NewInvestasi')->delete();
        return view('investasi.awal',compact('semuaInvestasi'));
    }

    public function create(){
        $jenisInvestasiPluck = JenisInvestasiModel::where('status','=','0')->pluck('nama', 'id');
        $anggotaPluck = AnggotaModel::where('status_keanggotaan','=','3')
                                    ->where('status_aktifasi','=','1')->get();
        return view('investasi.tambah', compact('jenisInvestasiPluck','anggotaPluck'));
    }

    public function store(InvestasiRequest $input){

        $investasi = new InvestasiModel($input->only('jenis_investasi_id','anggota_id'));

        //prngaturan format tanggal dari datepicker ke database format
        $tgl_pem = date('d-m-Y', strtotime($input->tanggal_pembayaran));
        $pembayaran = date('Y-m-d', strtotime($tgl_pem));   

        $investasi->jumlah = $input->jumlah;
        $investasi->tanggal_pembayaran = $pembayaran;
        $investasi->status = $input->status;
        $investasi->jenis_investasi_id = $input->jenis_investasi_id;
        $investasi->biaya_cetak_investasi = $input->biaya_cetak_investasi;

        //pengaturan path file
        $file = $input->file('foto_resi');
        $pic = time().'.'.$file->getClientOriginalExtension();
        $path = public_path('images/investasi/'.$pic);
        Image::make($file->getRealPath())->resize(468,249)->save($path);
        $investasi->foto_resi = 'images/investasi/'.$pic;             
        
        $informasi=$investasi->save() ? 'Berhasil simpan data' : 'Gagal simpan data';
        return redirect()->route('investasi.index')->with(['informasi'=>$informasi]);

    }

    public function edit($id){
        $investasi= InvestasiModel::findOrFail($id);
        $jenisInvestasiPluck = JenisInvestasiModel::pluck('nama', 'id');
        $anggotaPluck = AnggotaModel::where('status_keanggotaan','=','3')
                                    ->where('status_aktifasi','=','1')->get();
        return view('investasi.edit',compact('investasi','jenisInvestasiPluck', 'anggotaPluck'))->with(array('investasi'=>$investasi));
    }

    public function update($id, InvestasiRequest $input){
        // $validator = \Validator::make($input->all(), [
        //     'jumlah' => 'required|numeric',
        //     'anggota_id' => 'required|numeric',
        //     'jenis_investasi_id' => 'required|numeric',
        // ]);

        // if ($validator->fails()) {

        //     $informasi = 'Jumlah harus disi angka, nama anggota dan jenis investasi harus diisi';
        //     return redirect()->back()->with(['informasi' => $informasi]);

        // }
        $investasi = InvestasiModel::findOrFail($id);
        $investasi->anggota_id = $input->anggota_id;
        $investasi->jenis_investasi_id = $input->jenis_investasi_id;
        $investasi->jumlah = $input->jumlah;
        $investasi->biaya_cetak_investasi = $input->biaya_cetak_investasi;
        
            //jika foto resi tidak null
           if ($input->foto_resi != null) {
                // $validator = \Validator::make($input->all(), [
                // 'foto_resi' => 'mimes:jpeg,png,jpg,JPEG,JPG,PNG|max:2048|required',
                // ]);

                // if ($validator->fails()) {

                //     $informasi = 'Format file tidak didukung atau ukuran file lebih dari 2Mb. Pastikan format file adalah jpeg,png,jpg,JPEG,JPG,atau PNG ';
                //     return redirect()->back()->with(['informasi' => $informasi]);

                // }

            //pengaturan path file
            $file = $input->file('foto_resi');
            $pic = time() . '.' . $file->getClientOriginalExtension();
            $path = public_path('images/investasi/' . $pic);
            Image::make($file->getRealPath())->resize(468, 249)->save($path);
            $investasi->foto_resi = 'images/investasi/' . $pic;
           }

           //jika tanggal pembayaran tidak null
           if ($input->tanggal_pembayaran != null) {
                // $validator = \Validator::make($input->all(), [
                //     'tanggal_pembayaran' => 'date_format:"d-m-Y"|required',
                // ]);

                // if ($validator->fails()) {

                //     $informasi = 'Format tanggal pembayaran salah';
                //     return redirect()->back()->with(['informasi' => $informasi]);

                // }

                //pengaturan format tanggal dari datepicker ke database
                $tgl_pem = date('d-m-Y', strtotime($input->tanggal_pembayaran));
                $pembayaran = date('Y-m-d', strtotime($tgl_pem));  
                $investasi->tanggal_pembayaran = $pembayaran;
           }

            if ($investasi->save()) {
                $informasi = 'Berhasil update Data';
            } else {
                $informasi = 'Gagal update Data';
            }
            return redirect()->route('investasi.index')->with(['informasi'=>$informasi]);
    
}

    public function show($id){
        $investasi = InvestasiModel::findOrFail($id);
        return view('investasi.lihat')->with(array('investasi'=>$investasi));
    }

    public function destroy($id){
        $investasi= InvestasiModel::findOrFail($id);
        $informasi=$investasi->delete() ? 'Berhasil hapus data' : 'Gagal hapus data';
        return redirect()->route('investasi.index')->with(['informasi'=>$informasi]);

    }

    public function status($id,$status) {

        //mengubah status verifikasi investasi melalui klik tombol
        $investasi = InvestasiModel::findOrFail($id);
        $anggota= AnggotaModel::where('id','=',$investasi->anggota_id)->first();       
        $user= UserModel::where('id','=',$anggota->users_id)->first();        
        $update = $investasi->where('id',$id)->firstOrFail()->update(['status'=>$status]);
        if($status == 1) {
            $informasi = 'Investasi Berhasil Divalidasi';
            $message = 'Assalamualaikum wr. wb , Pembayaran investasi di '.$investasi->jenis_investasi->nama.' anda pada tanggal : '.$investasi->tanggal_pembayaran.' dengan jumlah : '.$investasi->jumlah.' telah tervalidasi. 212 Mart Samarinda';
            $sms = new \App\Helpers\Zenziva();
            $sms->send($anggota->no_telepon, $message);
        }
        else {
            $informasi = 'Investasi Batal Divalidasi';
        }

        //notifikasi ke navbar investor bahwa investasi dia telah di verifikasi
        $user->notify(new VerifikasiInvestasi());
        return redirect()->route('investasi.index')->with(['informasi'=>$informasi]);
    }

}

resources/views/investasi/awal.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="btn-group pull-right m-t-15">
                                        <a href="{{route('investasi.create')}}"> <button type="button" class="btn btn-default ">Tambah <span class="m-l-5"><i class=" fa fa-plus fa fa-cog"></i></span></button></a>
                                </div>

                                <ol class="breadcrumb">
                                    <li>
                                        <a href="#">Admin</a>
                                    </li>
                                    <li>
                                        <a href="#">Transaksi</a>
                                    </li>
                                    <li class="active">
                                        Investasi
                                    </li>
                                </ol>
                            </div>
                        </div>

                        <center><h4 class="m-t-0"><b>TABEL PEMBAYARAN INVESTASI</b></h4></center>

                        <!-- Form Pencarian -->
                        <form action="{{url()->current()}}">
                            <div class="container">
                                <div class="row">
                                    <div class="input-group col-12 col-md-4 pull-right">
                                        {!! Form::text('nama',null,['class'=>'form-control col-md-3','placeholder'=>"Nomor Anggota atau Nama"]) !!}          
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn waves-effect waves-light btn-primary">Cari</button>                                        
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <br>
                        <table id="datatable" class="table table-striped table-bordered">

                      	<!-- Alert -->
						@yield('alert')
					
                            <thead>
                                <tr>
                                    <th width="10%" scope="row">No</th>
                                    <th width="20%" scope="row">Nomor Anggota</th>
                                    <th width="20%" scope="row">Nama Anggota</th>
                                    <th width="30%" scope="row">Jenis Investasi</th>
                                    <th width="30%" scope="row">Jumlah</th>
                                    <th width="30%" scope="row">Tanggal Pembayaran</th>
                                    <th width="30%" scope="row">Validasi</th>
                                    <th width="30%" scope="row">Bukti Pembayaran</th>
                                    <th width="30%" scope="row">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @php
                                    $no =1+($semuaInvestasi->perPage()*($semuaInvestasi->currentPage()-1));
                                @endphp
                                @foreach($semuaInvestasi as $investasi)
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{$investasi->anggota->nomor_anggota or 'kosong'}}</td>
                                        <td>{{$investasi->anggota->nama or 'kosong'}}</td>
                                        <td>{{$investasi->jenis_investasi->nama or 'kosong'}}</td>
                                        <td>{{rupiah($investasi->jumlah)}}</td>
                                        <td>{{DateIndo($investasi->tanggal_pembayaran )}}</td>
                                        <td>
                                                @if($investasi->status == 1)
                                                <a href="{{ url('admin/ubah/investasi/'.$investasi->id.'/0') }}" class="yes" data-user="{{ $investasi->id }}" desc="Yakin nonaktifkan?">
                                                    <input checked type="checkbox" class="sip" get-user="{{ $investasi->id }}" data-color="#f05050" data-plugin="switchery" data-size="small"/>
                                                </a>
                                                @else
                                                <a href="{{ url('admin/ubah/investasi/'.$investasi->id.'/1') }}" class="yes" data-user="{{ $investasi->id }}" desc="Yakin ingin memveifikasi?">
                                                    <input type="checkbox" class="sip" get-user="{{ $investasi->id }}" data-color="#f05050" data-plugin="switchery" data-size="small"/>
                                                </a>
                                                @endif
                                        </td>
                                        <td>
                                            <div class="portfolioContainer">
                                                <div class="col-sm-6 col-lg-3 col-md-4 graphicdesign illustrator photography">
                                                    <a href="{{ asset($investasi->foto_resi)}}" class="image-popup" title="Resi Pembayaran {{$investasi->anggota->nomor_anggota}}">
                                                    <button class="btn btn-warning waves-effect waves-light"><i class="fa fa-eye m-r-5"></i>
                                                    <span>Resi</span></button></a>
                                                </div> 
                                            </div>     
                                        </td>

                                        <td>
                                            {{ Form::open(array('route' => array('investasi.destroy', $investasi->id), 'method' => 'delete')) }}
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-primary dropdown-toggle  waves-effect" data-toggle="dropdown" aria-expanded="false"> Aksi <span class="caret"></span> </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="{{route('investasi.edit', $investasi->id)}}">Ubah</a></li>
                                                        <li><a href="{{route('investasi.show', $investasi->id)}}">Lihat</a></li>
                                                        <button id="btn-action" class="btn btn-white waves-effect waves-light btn-xs" data-toggle="tooltip" data-placement="top" title="Delete">Hapus</button>
                                                    </ul>
                                                </div>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {!! $semuaInvestasi->appends(Request::except('page'))->render() !!}
                    </div>
                </div>
            </div>
        </div> <!-- container -->
    </div> <!-- content -->
</div><!-- End Right content here -->
@stop

resources/views/investasi/edit.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
	<!-- Start content -->
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-color panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title"> EDIT PEMBAYARAN INVESTASI</h3></a>
						</div>
						<div class= "container">
						<!-- Alert -->
						@yield('alert')
						<div>
						<div class="panel-body">
     						{{ Form::model($investasi, array('route' => array('investasi.update', $investasi->id), 'files' => true, 'method' => 'PUT','class'=>'form-horizontal')) }}
    	 						@include('investasi.form')
								 <div class="form-group">
										<div class="col-md-12">
											 <div class="col-md-offset-9 text-right">
													<a href="{{route('investasi.index')}}" class="btn btn-warning waves-effect waves-light" > 
															<i class="fa fa-arrow-left m-r-5"></i>
															<span>Batal</span>
														</a>
											   <button type="submit" class="btn btn-default waves-effect waves-light">
													   <i class="md-autorenew m-r-5"></i>
													   <span>Perbarui</span>
											   </button>

											 </div>
										</div>
								   </div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div> <!-- container -->

	</div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/investasi/form.blade.php
<div class="form-group">
	<label class="col-md-2 control-label">Tanggal Pembayaran</label>
	<div class="col-md-10">
		<div class="input-group">
			@php
			$tgl_conv = date('Y-m-d', strtotime($investasi->tanggal_pembayaran));
			$tgl_jadi = date('d-m-Y', strtotime($tgl_conv));
			@endphp
			<input type="text" name="tanggal_pembayaran" value="{{$tgl_jadi}}" class="form-control datepickerautoclose" placeholder="tgl-bln-tahun">
			<span class="input-group-addon bg-custom b-0 text-white"><i class="icon-calender"></i></span>
		</div>
	</div>
</div>
        
<div class="form-group">
	<label class="col-md-2 control-label">Jumlah</label>
	<div class="col-md-10">
		{!! Form::text('jumlah',null,['class'=>'form-control','placeholder'=>"Jumlah", 'required' ]) !!}
	</div>
</div>

<div class="form-group">
    <label class="col-md-2 control-label">Biaya cetak kartu & sertifikat</label>
    <div class="col-md-10">
        {{ Form::text('biaya_cetak_investasi', 50000,['class'=>'form-control','placeholder'=>"Biaya cetak kartu & sertifikat","readonly"]) }}
    </div>
</div>

<div class="form-group">
	<label class="col-md-2 control-label">Bukti Pembayaran</label>
	<div class="col-md-10">
		<input name = "foto_resi" type="file" class="filestyle" >
		<br>
		<img id="preview" style="margin-bottom: 5px;" src="{{ asset($investasi->foto_resi) }}" height="100" alt="">
		</input>
	</div>
</div>

<div class="form-group">
    <label class="col-md-2 control-label">Nama Anggota</label>
    <div class="col-md-10">
        <select class="form-control select2" name="anggota_id" id="">
        	@foreach ($anggotaPluck as $anggota )
           		<option value="{{ $anggota->id}}"
                @if ($anggota->id === $investasi->anggota_id)
                 	selected
                @endif
                  	>{{ $anggota->nama}} - {{ $anggota->nomor_anggota}} </option>
        	@endforeach
         </select>
    </div>
</div> 

<div class="form-group">
	<label class="col-md-2 control-label">Jenis Investasi</label>
	<div class="col-md-10">
		{{ Form::select('jenis_investasi_id', $jenisInvestasiPluck, null, ['class' => 'form-control']) }}
	</div>
</div>

resources/views/investasi/lihat.blade.php
@extends('master')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
     <!-- Start content -->
     <div class="content">
          <div class="container">
               <div class="row">
                    <div class="col-md-12">
                         <div class="panel panel-color panel-primary">
                              <div class="panel-heading">
                                   <h3 class="panel-title"> DETAIL PEMBAYARAN INVESTASI</h3></a>
                              </div>
                              <div class="panel-body">
                                   <table class="table">
                                        <tr>
                                            <td>Tanggal Pembayaran</td>
                                            <td>:</td>
                                            <td>{{DateIndo($investasi->tanggal_pembayaran)}}</td>
                                        </tr>

                                        <tr>
                                            <td>Jumlah</td>
                                            <td>:</td>
                                            <td>{{rupiah($investasi->jumlah)}}</td>
                                        </tr>

                                        <tr>
                                            <td>Bukti Pembayaran</td>
                                            <td>:</td>
                                            <td>
                                                <img alt="" src="{{ asset($investasi->foto_resi)}}" height="100px" weight="100px"/>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>Status</td>
                                            <td>:</td>
                                            @if($investasi->status != 0)
                                            <td>{{'Sudah tervalidasi'}}</td>
                                            @else
                                            <td>{{'Belum tervalidasi'}}</td>
                                            @endif
                                        </tr>

                                        <tr>
                                            <td>Nomor Anggota</td>
                                            <td>:</td>
                                            <td>{{$investasi->anggota->nomor_anggota}}</td>
                                        </tr>

                                        <tr>
                                            <td>Nama Anggota</td>
                                            <td>:</td>
                                            <td>{{$investasi->anggota->nama}}</td>
                                        </tr>
    
                                        <tr>
                                            <td>Jenis Investasi</td>
                                            <td>:</td>
                                            <td>{{$investasi->jenis_investasi->nama}}</td>
                                        </tr>
                                        
                                        <tr>
                                            <td class="col-xs-4">Create at</td>
                                            <td class="col-xs-1">:</td>
                                            <td>{{$investasi->created_at}}</td>
                                        </tr>
                                        <tr>
                                            <td class="col-xs-4">Update at</td>
                                            <td class="col-xs-1">:</td>
                                            <td>{{$investasi->updated_at}}</td>
                                        </tr>
                                    </table>

                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <div class="col-md-offset-9 text-right">
                                                <a href="{{route('investasi.index')}}">
                                                    <button class="btn btn-warning waves-effect waves-light">
                                                    <i class="fa fa-arrow-left m-r-5"></i><span>Kembali</span>
                                                    </button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                         </div>
                    </div>
               </div>
          </div> <!-- container -->

     </div> <!-- content -->

</div><!-- End Right content here -->
@stop