routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UtamaController@welcome')->name('/');
Route::get('/profil', 'UtamaController@tentang')->name('/profil');
Route::get('/struktur', 'UtamaController@struktur')->name('/struktur');
Route::get('/faq', 'UtamaController@faq')->name('/faq');
Route::get('/blog', 'UtamaController@blog')->name('/blog');
Route::get('/blog-one/{id}', 'UtamaController@blogOne')->name('blog-one');
Route::get('/page_doc', 'UtamaController@page_doc')->name('/page_doc');
Route::get('resource/download_dokumen', ['as' => 'resource.download', 'uses' => 'SessionController@download']);

Route::get('/login', 'SessionController@form')->name('login');
Route::post('/login', 'SessionController@validasi')->name('process_login');
Route::get('/logout', 'SessionController@logout')->name('logout');
Route::get('/registration', 'SessionController@registration')->name('registration');
Route::post('/registration', 'SessionController@registrationStore', ['middleware' => 'web'])->name('process_registration');

Route::group(['prefix' => 'anggota', 'middleware' => 'AnggotaMiddleware'], function () {
    Route::get('/', 'DashboardController@dashboard_anggota')->name('anggota');
    Route::resource('profil_anggota', 'AnggotaProfilController');
    Route::resource('password_anggota', 'UpdatePassword');
    Route::resource('simpanan_anggota', 'AnggotaPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_anggota', 'AnggotaDokumenController');
    Route::get('resource/download_anggota', ['as' => 'anggota.resource.download', 'uses' => 'AnggotaDokumenController@download']);
    Route::resource('belanja_anggota', 'BelanjaAnggotaController');
});

Route::group(['prefix' => 'investor', 'middleware' => 'InvestorMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'InvestorProfilController@getOmset');

    Route::get('/', 'DashboardController@dashboard_investor')->name('investor');
    Route::resource('profil', 'InvestorProfilController');
    Route::resource('password', 'UpdatePassword');
    Route::resource('simpanan', 'InvestorPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('investasis', 'InvestorInvestasiController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_investor', 'InvestorDokumenController');
    Route::get('resource/download_investor', ['as' => 'investor.resource.download', 'uses' => 'InvestorDokumenController@download']);
    Route::resource('belanja_investor', 'BelanjaInvestorController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'AdminMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'AnggotaController@getOmset');

    Route::get('/', 'DashboardController@dashboard_admin')->name('admin');

    //route laporan unit usaha
    Route::get('/download/{jenis}/{id}', array('as' => 'download', 'uses' => 'LaporanController@download'));
    Route::get('/pdfview/{id}', array('as' => 'pdfview', 'uses' => 'LaporanController@pdfview'));
    Route::get('/iniLaporan', 'LaporanController@iniLaporan')->name('iniLaporan');

    Route::resource('role', 'RoleController', ['except' => [
    'create', 'store', 'destroy',
    ]]);

    Route::resource('user', 'UserController');

    Route::resource('anggota', 'AnggotaController');

    Route::get('anggota/simpanan/{id}', 'AdminAnggotaSimpanan@awal')->name('anggota.simpanan');
    Route::get('anggota/investasi/{id}', 'AdminAnggotaInvestasi@awal')->name('anggota.investasi');

    Route::get('/ubah/anggota/{id}/{status}', 'AnggotaController@status');

    Route::resource('jabatan', 'JabatanController');

    Route::resource('jenis_investasi', 'JenisInvestasiController');

    Route::resource('jenis_pembayaran', 'JenisPembayaranController');

    Route::resource('investasi', 'InvestasiController');
    Route::resource('omset', 'OmsetController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('resource/download', ['as' => 'admin.resource.download', 'uses' => 'DokumenController@download']);

    Route::resource('pembayaran', 'PembayaranController');

    Route::get('/ubah/pembayaran/{id}/{status}', 'PembayaranController@status');

    Route::get('/ubah/investasi/{id}/{status}', 'InvestasiController@status');

    Route::get('/ubah/pengambilan/{id}/{status}', 'PengambilanController@status');

    Route::resource('kepengurusan', 'KepengurusanController');

    Route::resource('penjualan', 'PenjualanController', ['except' => ['show', 'edit', 'destroy']]);

    Route::resource('pengambilan', 'PengambilanController');

    Route::resource('visimisi', 'VisimisiController');

    Route::resource('badanhukum', 'BadanhukumController');

    Route::resource('ketentuan', 'KetentuanController');

    Route::resource('faq', 'FaqController');

    Route::resource('berita', 'BeritaController');

    Route::resource('shu', 'ShuController');

    Route::resource('dewan', 'DewanController');
    Route::resource('belanja', 'BelanjaController');

    Route::get('data-omset','DataOmsetController@dataOmset')->name('data.omset');
    Route::get('data-anggota-tahunan','DataOmsetController@dataAnggotaTahunan')->name('data.anggota.tahunan');
    Route::get('data-keuntungan-tahunan','DataOmsetController@dataKeuntunganTahunan')->name('data.keuntungan.tahunan');

});

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/kirim-sms', function (){
//    $sms = new \App\Helpers\Zenziva();
  //  $sms->send('085652095696','test kirim zenziva sms');
//});

Route::get('/generate-barcode', function () {
    $anggota = new \App\Model\AnggotaModel();
    //use Milon\Barcode\DNS1D;
    $barcode = new \Milon\Barcode\DNS1D();
    $i = 0;
    foreach ($anggota->get() as $row) {
        ++$i;
        //echo '<img src="data:image/png;base64,' . $barcode->getBarcodePNG($row->nomor_anggota, "C128",2,33,array(1,1,1), true) . '" alt="barcode"   />';

        $barcode->setStorPath(storage_path('/app/images/barcode_anggota/'.$row->nama.'_'));
        $img = $barcode->getBarcodePNGPath($row->nomor_anggota, 'C128', 2, 33);
        //echo $barcode->getBarcodePNGPath($row->nomor_anggota, "C128",3,33,array(255,255,0), true);
        // return response($img.'<br>');
        echo $row->nomor_anggota.'<br>';
    }
});

Route::get('/ajax-chart-anggota', 'DashboardController@ajaxChartAnggota')->name('get.ajaxAnggota');
Route::get('/ajax-chart-line-omzet', 'DashboardController@ajaxLineOmzet')->name('get.ajaxLineOmzet');
Route::get('/ajax-change-toko', 'DashboardController@changeToko')->name('get.changeToko');

app/Http/Controllers/DokumenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Model\DokumenModel;
use Intervention\Image\ImageManagerStatic as Image;
use \Intervention\Image\File;
use App\Http\Requests\DokumenRequest;


class DokumenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // $semuaDokumen = DokumenModel::all();
        $semuaDokumen = DokumenModel::Cari($request)->paginate(5);
        return view('dokumen.awal', compact('semuaDokumen'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dokumen.tambah');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DokumenRequest $input)
    {
        // $validator = \Validator::make($input->all(), [
        //     'file_dokumen' => 'mimes:pdf,doc,docx,ppt,pptx,xls,xlsx|max:2048|required'
        // ]);

        // if ($validator->fails()) {

        //     $informasi = 'Format file tidak didukung atau ukuran file lebih dari 2Mb. Pastikan format file adalah pdf,doc,docx,ppt,pptx,xls,atau xlsx ';
        //     return redirect()->back()->with(['informasi' => $informasi]);

        // }
        $dokumen = new DokumenModel($input->only('judul','deskripsi'));
        $file = $input->file('file_dokumen');
        // $pic = time() . '.' . $file->getClientOriginalExtension();
        $pic = $file->getClientOriginalName();
        
        $file->move(public_path('file/'), $pic);



        // $dokumen->file_dokumen = 'file/'.$pic;
        $dokumen->file_dokumen = $pic;

        $informasi = $dokumen->save() ? 'Berhasil simpan data' : 'Gagal simpan data';
        return redirect()->route('dokumen.index')->with(['informasi' => $informasi]);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dokumen = DokumenModel::findOrFail($id);
        return view('dokumen.lihat')->with(array('dokumen' => $dokumen));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dokumen = DokumenModel::findOrFail($id);
        return view('dokumen.edit')->with(array('dokumen' => $dokumen));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DokumenRequest $input, $id)
    {
        $dokumen = DokumenModel::findOrFail($id);
        $dokumen->judul=$input->judul;
        $dokumen->deskripsi = $input->deskripsi;
        if($input->file('file_dokumen') != null){
        $file = $input->file('file_dokumen');
        $pic = time() . '.' . $file->getClientOriginalExtension();
        // $path = public_path('file/' . $pic);

        $file->move(public_path('file/'), $pic);
        // $dokumen->file_dokumen = 'file/' . $pic;
        $dokumen->file_dokumen = $pic;
        }

        $informasi = $dokumen->save() ? 'Berhasil update data' : 'Gagal update data';
        return redirect()->route('dokumen.index')->with(['informasi' => $informasi]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dokumen = DokumenModel::findOrFail($id);
        $informasi = $dokumen->delete() ? 'Berhasil hapus data' : 'Gagal hapus data';
        return redirect()->route('dokumen.index')->with(['informasi' => $informasi]);
    }

    public function download(Request $request)
    {
        return response()->download(public_path('/file/' . $request['file']));  
    }
}

resources/views/dokumen/awal.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                            <div class="row">
                                    <div class="col-sm-12">
                                        <div class="btn-group pull-right m-t-15">
                                                <a href="{{route('dokumen.create')}}"> <button type="button" class="btn btn-default ">Tambah <span class="m-l-5"><i class=" fa fa-plus fa fa-cog"></i></span></button></a>
                                        </div>
        
                                        <ol class="breadcrumb">
                                            <li>
                                                <a href="#">Admin</a>
                                            </li>
                                            <li class="active">
                                                Dokumen
                                            </li>
                                        </ol>
                                    </div>
                                </div>

                        <center><h4 class="m-t-0"><b>TABEL DOKUMEN</b></h4></center>

                        <!-- Search -->
                            <form action="{{url()->current()}}">
                                <div class="container">
                                    <div class="row">
                                        <div class="input-group col-12 col-md-4 pull-right">
                                            {!! Form::text('judul',null,['class'=>'form-control col-md-3','placeholder'=>"Nama"]) !!}          
                                            <span class="input-group-btn">
                                                <button type="submit" class="btn waves-effect waves-light btn-primary">Cari</button>                                        
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        <!-- End Search -->

                        <table id="datatable" class="table table-striped table-bordered">

                           	<!-- Alert -->
							    @yield('alert')
							<!-- End Alert -->

                            <thead>
                                <tr>
                                    <th width="5%" scope="row">No</th>
                                    <th width="20%" scope="row">Nama</th>
                                    <th width="20%" scope="row">Deskripsi</th>
                                    <th width="40%" scope="row">File</th>
                                    <th width="20%" scope="row">Action</th>
                                </tr>
                            </thead>


                            <tbody>
                                @php
                                    $no =1;
                                @endphp
                               
                                @foreach($semuaDokumen as $dokumen)
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{$dokumen->judul or 'kosong'}}</td>
                                        <td>{{$dokumen->deskripsi or 'kosong'}}</td>
                                        <td>
                                            <a href="{{ route('admin.resource.download', array('file'=>$dokumen->file_dokumen)) }}">{{$dokumen->file_dokumen}}</a>
                                        </td>
                                        <td>
                                            {{ Form::open(array('route' => array('dokumen.destroy', $dokumen->id), 'method' => 'delete')) }}
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-primary dropdown-toggle  waves-effect" data-toggle="dropdown" aria-expanded="false"> Aksi <span class="caret"></span> </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="{{route('dokumen.edit', $dokumen->id)}}">Ubah</a></li>
                                                        <li><a href="{{route('dokumen.show', $dokumen->id)}}">Lihat</a></li>
                                                        <button id="btn-action" class="btn btn-white waves-effect waves-light btn-xs" data-toggle="tooltip" data-placement="top" title="Hapus">Hapus</button>
                                                    </ul>
                                                </div>
                                            {{ Form::close() }}
                                        </td>
                                        
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {!!  $semuaDokumen->appends(Request::except('page'))->render() !!}
                    </div>
                </div>
            </div>
        </div> <!-- container -->

    </div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/dokumen/edit.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
	<!-- Start content -->
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-color panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title"> EDIT DOKUMEN</a>
						</div>
						<div class="panel-body">
     						{{ Form::model($dokumen, array('route' => array('dokumen.update', $dokumen->id), 'files' => true, 'method' => 'PUT','class'=>'form-horizontal')) }}
								<div class= "container">
								<!-- Alert -->
									@yield('alert')
								</div>	 
							 	@include('dokumen.form')
								 <div class="form-group">
										<div class="col-md-12">
											 <div class="col-md-offset-9 text-right">
													<a href="{{route('dokumen.index')}}" class="btn btn-warning waves-effect waves-light" > 
															<i class="fa fa-arrow-left m-r-5"></i>
															<span>Batal</span>
													</a>
												   
											   <button type="submit" class="btn btn-default waves-effect waves-light">
													   <i class="md-autorenew m-r-5"></i>
													   <span>Perbarui</span>
											   </button>

											 </div>
										</div>
								   </div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div> <!-- container -->

	</div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/dokumen/form.blade.php
<div class="form-group">
     <label class="col-md-2 control-label">Judul</label>
     <div class="col-md-10">
        {!! Form::text('judul',old('judul'),['class'=>'form-control','placeholder'=>"Judul"]) !!}
     </div>
</div>
<div class="form-group">
    <label class="col-md-2 control-label">Deskripsi</label>
    <div class="col-md-10">
        {!! Form::textarea('deskripsi',old('deskripsi'),['class'=>'form-control','placeholder'=>"Deskripsi",'id'=> 'elm1']) !!}
    </div>
</div>
<div class="form-group">
    <label class="col-md-2 control-label">Upload Dokumen<span class="text-danger">*</label>
    <div class="col-md-10">
        <input name = "file_dokumen" value="<?= Form::old('file_dokumen') ?>" type="file" class="filestyle">
    </div>
</div>

resources/views/dokumen/lihat.blade.php
@extends('master')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
     <!-- Start content -->
     <div class="content">
          <div class="container">
               <div class="row">
                    <div class="col-md-12">
                         <div class="panel panel-color panel-primary">
                              <div class="panel-heading">
                                 <h3 class="panel-title"> DETAIL Dokumen</h3></a>
                              </div>
                              <div class="panel-body">
                                   <table class="table">
                                        <tr>
                                            <td>Judul</td>
                                            <td>:</td>
                                            <td>{{$dokumen->judul}}</td>
                                        </tr>
                                        <tr>
                                            <td>Deskripsi</td>
                                            <td>:</td>
                                            <td>{{$dokumen->deskripsi}}</td>
                                        </tr>
                                       <tr>
                                             <td>Dokumen</td>
                                             <td>:</td>
                                             <td>
                                                <a href="{{ route('admin.resource.download', array('file'=>$dokumen->file_dokumen)) }}">{{$dokumen->file_dokumen}}</a>
                                            </td>
                                        </tr>
                                        

                                        <tr>
                                            <td class="col-xs-4">Create at</td>
                                            <td class="col-xs-1">:</td>
                                            <td>{{$dokumen->created_at}}</td>
                                        </tr>
                                        <tr>
                                            <td class="col-xs-4">Update at</td>
                                            <td class="col-xs-1">:</td>
                                            <td>{{$dokumen->updated_at}}</td>
                                        </tr>
                                   </table>
                                   <div class="form-group">
                                        <div class="col-md-12">
                                            <div class="col-md-offset-9 text-right">
                                             <a href="{{route('dokumen.index')}}">
                                                 <button class="btn btn-warning waves-effect waves-light">
                                                    <i class="fa fa-arrow-left m-r-5"></i><span>Kembali</span>
                                                 </button></a>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                         </div>
                    </div>
               </div>
          </div> <!-- container -->

     </div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/dokumen/tambah.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
	<!-- Start content -->
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-color panel-primary">
						<div class="panel-heading">
							<a href="{{route('dokumen.index')}}"><h3 class="panel-title"><i class="fa  fa-arrow-left"></i></h3></a>
						</div>
						<div class="panel-body">
							{!! Form::open(['route'=>'dokumen.store','class'=>'form-horizontal','files'=>true]) !!}
								<div class= "container">
								<!-- Alert -->
									@yield('alert')
								</div>
								<center><h4 class="m-t-0"><b>TAMBAH DOKUMEN</b></h4></center>
									<br>
    							@include('dokumen.form')
								<div class="form-group">
										<div class="col-md-12">
											<div class="form-group">
												<div class="col-md-12">
													<div class="col-md-offset-9 text-right">
														<button type="reset" class="btn btn-danger waves-effect waves-light">
															<span class="btn-label"><i class="fa fa-repeat"></i>
															</span>Ulangi
														</button>
														<button type="submit" class="btn btn-default waves-effect waves-light">
															<i class="fa fa-save m-r-5"></i>
															<span>Simpan</span>
														</button>
													</div>
												</div>
											</div>
										</div>
									</div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div> <!-- container -->
	</div> <!-- content -->
</div><!-- End Right content here -->
@stop