routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UtamaController@welcome')->name('/');
Route::get('/profil', 'UtamaController@tentang')->name('/profil');
Route::get('/struktur', 'UtamaController@struktur')->name('/struktur');
Route::get('/faq', 'UtamaController@faq')->name('/faq');
Route::get('/blog', 'UtamaController@blog')->name('/blog');
Route::get('/blog-one/{id}', 'UtamaController@blogOne')->name('blog-one');
Route::get('/page_doc', 'UtamaController@page_doc')->name('/page_doc');
Route::get('resource/download_dokumen', ['as' => 'resource.download', 'uses' => 'SessionController@download']);

Route::get('/login', 'SessionController@form')->name('login');
Route::post('/login', 'SessionController@validasi')->name('process_login');
Route::get('/logout', 'SessionController@logout')->name('logout');
Route::get('/registration', 'SessionController@registration')->name('registration');
Route::post('/registration', 'SessionController@registrationStore', ['middleware' => 'web'])->name('process_registration');

Route::group(['prefix' => 'anggota', 'middleware' => 'AnggotaMiddleware'], function () {
    Route::get('/', 'DashboardController@dashboard_anggota')->name('anggota');
    Route::resource('profil_anggota', 'AnggotaProfilController');
    Route::resource('password_anggota', 'UpdatePassword');
    Route::resource('simpanan_anggota', 'AnggotaPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_anggota', 'AnggotaDokumenController');
    Route::get('resource/download_anggota', ['as' => 'anggota.resource.download', 'uses' => 'AnggotaDokumenController@download']);
    Route::resource('belanja_anggota', 'BelanjaAnggotaController');
});

Route::group(['prefix' => 'investor', 'middleware' => 'InvestorMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'InvestorProfilController@getOmset');

    Route::get('/', 'DashboardController@dashboard_investor')->name('investor');
    Route::resource('profil', 'InvestorProfilController');
    Route::resource('password', 'UpdatePassword');
    Route::resource('simpanan', 'InvestorPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('investasis', 'InvestorInvestasiController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_investor', 'InvestorDokumenController');
    Route::get('resource/download_investor', ['as' => 'investor.resource.download', 'uses' => 'InvestorDokumenController@download']);
    Route::resource('belanja_investor', 'BelanjaInvestorController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'AdminMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'AnggotaController@getOmset');

    Route::get('/', 'DashboardController@dashboard_admin')->name('admin');

    //route laporan unit usaha
    Route::get('/download/{jenis}/{id}', array('as' => 'download', 'uses' => 'LaporanController@download'));
    Route::get('/pdfview/{id}', array('as' => 'pdfview', 'uses' => 'LaporanController@pdfview'));
    Route::get('/iniLaporan', 'LaporanController@iniLaporan')->name('iniLaporan');

    Route::resource('role', 'RoleController', ['except' => [
    'create', 'store', 'destroy',
    ]]);

    Route::resource('user', 'UserController');

    Route::resource('anggota', 'AnggotaController');

    Route::get('anggota/simpanan/{id}', 'AdminAnggotaSimpanan@awal')->name('anggota.simpanan');
    Route::get('anggota/investasi/{id}', 'AdminAnggotaInvestasi@awal')->name('anggota.investasi');

    Route::get('/ubah/anggota/{id}/{status}', 'AnggotaController@status');

    Route::resource('jabatan', 'JabatanController');

    Route::resource('jenis_investasi', 'JenisInvestasiController');

    Route::resource('jenis_pembayaran', 'JenisPembayaranController');

    Route::resource('investasi', 'InvestasiController');
    Route::resource('omset', 'OmsetController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('resource/download', ['as' => 'admin.resource.download', 'uses' => 'DokumenController@download']);

    Route::resource('pembayaran', 'PembayaranController');

    Route::get('/ubah/pembayaran/{id}/{status}', 'PembayaranController@status');

    Route::get('/ubah/investasi/{id}/{status}', 'InvestasiController@status');

    Route::get('/ubah/pengambilan/{id}/{status}', 'PengambilanController@status');

    Route::resource('kepengurusan', 'KepengurusanController');

    Route::resource('penjualan', 'PenjualanController', ['except' => ['show', 'edit', 'destroy']]);

    Route::resource('pengambilan', 'PengambilanController');

    Route::resource('visimisi', 'VisimisiController');

    Route::resource('badanhukum', 'BadanhukumController');

    Route::resource('ketentuan', 'KetentuanController');

    Route::resource('faq', 'FaqController');

    Route::resource('berita', 'BeritaController');

    Route::resource('shu', 'ShuController');

    Route::resource('dewan', 'DewanController');
    Route::resource('belanja', 'BelanjaController');

    Route::get('data-omset','DataOmsetController@dataOmset')->name('data.omset');
    Route::get('data-anggota-tahunan','DataOmsetController@dataAnggotaTahunan')->name('data.anggota.tahunan');
    Route::get('data-keuntungan-tahunan','DataOmsetController@dataKeuntunganTahunan')->name('data.keuntungan.tahunan');

});

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/kirim-sms', function (){
//    $sms = new \App\Helpers\Zenziva();
  //  $sms->send('085652095696','test kirim zenziva sms');
//});

Route::get('/generate-barcode', function () {
    $anggota = new \App\Model\AnggotaModel();
    //use Milon\Barcode\DNS1D;
    $barcode = new \Milon\Barcode\DNS1D();
    $i = 0;
    foreach ($anggota->get() as $row) {
        ++$i;
        //echo '<img src="data:image/png;base64,' . $barcode->getBarcodePNG($row->nomor_anggota, "C128",2,33,array(1,1,1), true) . '" alt="barcode"   />';

        $barcode->setStorPath(storage_path('/app/images/barcode_anggota/'.$row->nama.'_'));
        $img = $barcode->getBarcodePNGPath($row->nomor_anggota, 'C128', 2, 33);
        //echo $barcode->getBarcodePNGPath($row->nomor_anggota, "C128",3,33,array(255,255,0), true);
        // return response($img.'<br>');
        echo $row->nomor_anggota.'<br>';
    }
});

Route::get('/ajax-chart-anggota', 'DashboardController@ajaxChartAnggota')->name('get.ajaxAnggota');
Route::get('/ajax-chart-line-omzet', 'DashboardController@ajaxLineOmzet')->name('get.ajaxLineOmzet');
Route::get('/ajax-change-toko', 'DashboardController@changeToko')->name('get.changeToko');

app/Http/Controllers/PembayaranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\PembayaranModel;
use App\Model\JenisPembayaranModel;
use App\Model\AnggotaModel;
use App\Model\UserModel;
use App\Model\NotificationsModel;
use App\Notifications\VerifikasiPembayaran;
use Intervention\Image\ImageManagerStatic as Image;
use App\Http\Requests\PembayaranRequest;

class PembayaranController extends Controller
{
    public function index(Request $request)
    {
        $allPembayaran = PembayaranModel::Cari($request)->orderBy('id', 'DESC')->paginate(10);

        //notifikasi pembayaran baru di navbar dihapus
        $del_new_bayar = NotificationsModel::where('type', '=', 'App\Notifications\NewPembayaran')->delete();

        return view('pembayaran.awal', compact('allPembayaran'));
    }

    public function create()
    {
        $jenisPembayaranPluck = JenisPembayaranModel::pluck('nama', 'id');
        $anggotaPluck = AnggotaModel::where('status_aktifasi', '=', '1')->get();
        $jenisPokok = JenisPembayaranModel::where('id', '=', '1')->first();
        $jenisWajib = JenisPembayaranModel::where('id', '=', '2')->first();

        return view('pembayaran.tambah', compact('jenisPembayaranPluck','anggotaPluck',
                                    'jenisPokok', 'jenisWajib'));
    }

    public function store(Request $input)
    {
        $pembayaran = new PembayaranModel($input->only('anggota_id'));

        //jika jenis pembayaran yang diinput simpanan pokok
        if ($input->jbayar == 1) {
            $validator = \Validator::make($input->all(), [
                'jumlahP' => 'required|numeric',
            ]);
            if ($validator->fails()) {
                $informasi = 'Jumlah harus angka';

                return redirect()->back()->with(['informasi' => $informasi]);
            }
            $pembayaran->jumlah = $input->jumlahP;

            //jika jenis pembayaran yang diinput simpanan wajib
        } elseif ($input->jbayar == 2) {
            $validator = \Validator::make($input->all(), [
                'jumlahW' => 'required|numeric',
            ]);
            if ($validator->fails()) {
                $informasi = 'Jumlah harus angka';

                return redirect()->back()->with(['informasi' => $informasi]);
            }
            $pembayaran->jumlah = $input->jumlahW;

            //jika jenis pembayaran yang diinput simpanan sukarela
        } else {
            $validator = \Validator::make($input->all(), [
                'jumlah' => 'required|numeric',
            ]);
            if ($validator->fails()) {
                $informasi = 'Jumlah harus angka';

                return redirect()->back()->with(['informasi' => $informasi]);
            }
            $pembayaran->jumlah = $input->jumlah;
        }

        //format tanggal datepicker diubah ke database format
        $tgl_bayar = date('d-m-Y', strtotime($input->tanggal_pembayaran));
        $tglpembayaran = date('Y-m-d', strtotime($tgl_bayar));

        $pembayaran->jenis_pembayaran_id = $input->jbayar;
        $pembayaran->tanggal_pembayaran = $input->tanggal_pembayaran;
        $pembayaran->status = $input->status;

        // tempo ambil dari tempo sesuai jenis pembayaran yang diinput
        $jenis_pembayaran = JenisPembayaranModel::where('id', '=', $input->jbayar)->first();
        $lama_tempo = $jenis_pembayaran->lama_tempo;
        $pembayaran->tanggal_pembayaran = $tglpembayaran;
        $tgl = date('Y-m-d', strtotime("$tglpembayaran+$lama_tempo months"));
        $pembayaran->tanggal_tempo = $tgl;

        //input file resi
        $file = $input->file('file_resi');
        $pic = time().'.'.$file->getClientOriginalExtension();
        $path = public_path('images/pembayaran/'.$pic);
        Image::make($file->getRealPath())->resize(468, 249)->save($path);
        $pembayaran->file_resi = 'images/pembayaran/'.$pic;
        $informasi = $pembayaran->save() ? 'Berhasil simpan data' : 'Gagal simpan data';

        return redirect()->route('pembayaran.index')->with(['informasi' => $informasi]);
    }

    public function edit($id)
    {
        $pembayaran = PembayaranModel::findOrFail($id);
        $jenisPembayaranPluck = JenisPembayaranModel::pluck('nama', 'id');
        $anggotaPluck = AnggotaModel::where('status_aktifasi', '=', '1')->get();

        return view('pembayaran.edit', compact('pembayaran', 'jenisPembayaranPluck', 'anggotaPluck'))->with(array('pembayaran' => $pembayaran));
    }

    public function update($id, PembayaranRequest $input)
    {
        $pembayaran = PembayaranModel::findOrFail($id);

        // $validator = \Validator::make($input->all(), [
        //     'status' => 'required|numeric',
        //     'jumlah' => 'required|numeric',
        //     'anggota_id' => 'required|numeric',
        // ]);
        // if ($validator->fails()) {
        //     $informasi = 'Jumlah harus diisi angka, status pembayaran dan nama anggota harus diisi';

        //     return redirect()->back()->with(['informasi' => $informasi]);
        // }

        $pembayaran->anggota_id = $input->anggota_id;
        $pembayaran->jumlah = $input->jumlah;
        $pembayaran->status = $input->status;

        if ($input->tanggal_pembayaran != null) {
            $tgl_bayar = date('d-m-Y', strtotime($input->tanggal_pembayaran));
            $tglpembayaran = date('Y-m-d', strtotime($tgl_bayar));
            $pembayaran->tanggal_pembayaran = $tglpembayaran;
            $tmp = $pembayaran->jenis_pembayaran_id;

            //tempo
            $jenis_pembayaran = JenisPembayaranModel::where('id', '=', $tmp)->first();
            $lama_tempo = $jenis_pembayaran->lama_tempo;
            $bayar = $pembayaran->tanggal_pembayaran;
            $tgl = date('Y-m-d', strtotime("$bayar+$lama_tempo months"));
            $pembayaran->tanggal_tempo = $tgl;
        }

        //jika inputan file resi tidak null
        if ($input->file_resi != null) {
            $validator = \Validator::make($input->all(), [
                'file_resi' => 'mimes:jpeg,png,jpg,JPEG,JPG,PNG|max:2048|required',
            ]);

            if ($validator->fails()) {
                $informasi = 'File resi harus jpeg,png,jpg,JPEG,JPG, atau PNG dan file resi maksimal 2048kb';

                return redirect()->back()->with(['informasi' => $informasi]);
            }

            //pengaturan path gambar
            $file = $input->file('file_resi');
            $pic = time().'.'.$file->getClientOriginalExtension();
            $path = public_path('images/pembayaran/'.$pic);
            Image::make($file->getRealPath())->resize(468, 249)->save($path);
            $pembayaran->file_resi = 'images/pembayaran/'.$pic;
        }

        if ($pembayaran->save()) {
            $informasi = 'Berhasil update Data';
        } else {
            $informasi = 'Gagal update Data';
        }

        return redirect()->route('pembayaran.index')->with(['informasi' => $informasi]);
    }

    public function show($id)
    {
        $pembayaran = PembayaranModel::findOrFail($id);

        return view('pembayaran.lihat')->with(array('pembayaran' => $pembayaran));
    }

    public function destroy($id)
    {
        $pembayaran = PembayaranModel::findOrFail($id);
        $informasi = $pembayaran->delete() ? 'Berhasil hapus data' : 'Gagal hapus data';

        return redirect()->route('pembayaran.index')->with(['informasi' => $informasi]);
    }

    public function status($id, $status)
    {
        //status pembayaran diubah melalui klik tombol
        $pembayaran = PembayaranModel::findOrFail($id);
        $anggota = AnggotaModel::where('id', '=', $pembayaran->anggota_id)->first();
        $user = UserModel::where('id', '=', $anggota->users_id)->first();

        $update = $pembayaran->where('id', $id)->firstOrFail()->update(['status' => $status]);
        if ($status == 1) {
            $informasi = 'Pembayaran Berhasil Divalidasi';
            $message = 'Assalamualaikum wr. wb , Pembayaran '.$pembayaran->jenis_pembayaran->nama.' anda pada tanggal : '.$pembayaran->tanggal_pembayaran.' dengan jumlah : '.$pembayaran->jumlah.' telah tervalidasi. 212 Mart Samarinda';
            $sms = new \App\Helpers\Zenziva();
            $sms->send($anggota->no_telepon, $message);
        } else {
            $informasi = 'Pembayaran Batal Divalidasi';
        }

        //notif ke halaman anggota jika pembayaran telah diverifikasi
        $user->notify(new VerifikasiPembayaran());

        return redirect()->route('pembayaran.index')->with(['informasi' => $informasi]);
    }
}

resources/views/pembayaran/awal.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="btn-group pull-right m-t-15">
                                        <a href="{{route('pembayaran.create')}}"> <button type="button" class="btn btn-default ">Tambah <span class="m-l-5"><i class=" fa fa-plus fa fa-cog"></i></span></button></a>
                                </div>

                                <ol class="breadcrumb">
                                    <li>
                                        <a href="#">Admin</a>
                                    </li>

                                    <li>
                                        <a href="#">Transaksi</a>
                                    </li>

                                    <li class="active">
                                        Simpanan
                                    </li>
                                </ol>
                            </div>
                        </div>

                        <center><h4 class="m-t-0"><b>TABEL PEMBAYARAN SIMPANAN</b></h4></center>

                        <!-- Form Pencarian  -->
                        <form action="{{url()->current()}}">
                            <div class="container">
                                <div class="row">
                                    <div class="input-group col-12 col-md-4 pull-right">
                                        {!! Form::text('nama',null,['class'=>'form-control col-md-3','placeholder'=>"Nomor Anggota atau Nama"]) !!}          
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn waves-effect waves-light btn-primary">Cari</button>                                        
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <br>
                        
                        <table id="datatable" class="table table-striped table-bordered">
                                
                            <!-- Alert -->
                            @yield('alert')
                                 
                            
                            <thead>
                                <tr>
                                    <th width="5%" scope="row">No</th>
                                    <th width="15%" scope="row">Nomor Anggota</th>
                                    <th width="15%" scope="row">Nama Anggota</th>
                                    <th width="20%" scope="row">Jenis Simpanan</th>
                                    <th width="10%" scope="row">Jumlah Pembayaran</th>
                                    <th width="10%" scope="row">Tempo</th>
                                    <th width="20%" scope="row">Tanggal Pembayaran</th>
                                    <th width="10%" scope="row">Validasi</th>
                                    <th width="20%" scope="row">Bukti Pembayaran</th>
                                    <th width="10%" scope="row">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @php
                                    $no =1+($allPembayaran->perPage()*($allPembayaran->currentPage()-1));
                                @endphp
                                @foreach($allPembayaran as $pembayaran)
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{$pembayaran->anggota->nomor_anggota or 'kosong'}}</td>
                                        <td>{{$pembayaran->anggota->nama or 'kosong'}}</td>
                                        <td>{{$pembayaran->jenis_pembayaran->nama or 'kosong'}}</td>
                                        <td>{{rupiah($pembayaran->jumlah)}}</td>
                                        <td>{{DateIndo($pembayaran->tanggal_tempo)}}</td>
                                        <td>{{DateIndo($pembayaran->tanggal_pembayaran)}}</td>
                                        <td>
                                            @if($pembayaran->status == 1)
                                            <a href="{{ url('admin/ubah/pembayaran/'.$pembayaran->id.'/0') }}" class="yes" data-user="{{ $pembayaran->id }}" desc="Yakin batalkan validasi?">
                                                <input checked type="checkbox" class="sip" get-user="{{ $pembayaran->id }}" data-color="#f05050" data-plugin="switchery" data-size="small"/>
                                            </a>
                                            @else
                                            <a href="{{ url('admin/ubah/pembayaran/'.$pembayaran->id.'/1') }}" class="yes" data-user="{{ $pembayaran->id }}" desc="Yakin ingin memvalidasi?">
                                                <input type="checkbox" class="sip" get-user="{{ $pembayaran->id }}" data-color="#f05050" data-plugin="switchery" data-size="small"/>
                                            </a>
                                            @endif
                                        </td>
                                        <td>
                                            <div class="portfolioContainer">
                                                <div class="col-sm-6 col-lg-3 col-md-4 graphicdesign illustrator photography">
                                                     <a href="{{ asset($pembayaran->file_resi)}}" class="image-popup" title="Resi Pembayaran {{$pembayaran->anggota->nomor_anggota}}">
                                                        <button class="btn btn-warning waves-effect waves-light"><i class="fa fa-eye m-r-5"></i>
                                                        <span>Resi</span></button></a>
                                                </div> 
                                            </div>     
                                        </td>
                                        <td>
                                            {{ Form::open(array('route' => array('pembayaran.destroy', $pembayaran->id), 'method' => 'delete')) }}
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-primary dropdown-toggle  waves-effect" data-toggle="dropdown" aria-expanded="false"> Aksi <span class="caret"></span> </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="{{route('pembayaran.edit', $pembayaran->id)}}">Ubah</a></li>
                                                        <li><a href="{{route('pembayaran.show', $pembayaran->id)}}">Lihat</a></li>
                                                        <button id="btn-action" class="btn btn-white waves-effect waves-light btn-xs" data-toggle="tooltip" data-placement="top" title="Hapus">Hapus</button>
                                                    </ul>
                                                </div>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        
                        <!-- Render Pagination -->
                        {!! $allPembayaran->appends(Request::except('page'))->render() !!}
                    </div>
                </div>
            </div>
        </div> <!-- container -->
    </div> <!-- content -->
</div><!-- End Right content here -->
@stop

resources/views/pembayaran/edit.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
	<!-- Start content -->
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-color panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title"> EDIT PEMBAYARAN SIMPANAN</h3></a>
						</div>
						<div class="panel-body">
     						{{ Form::model($pembayaran, array('route' => array('pembayaran.update', $pembayaran->id), 'files' => true, 'method' => 'PUT','class'=>'form-horizontal')) }}
								<div class= "container">
								<!-- Alert -->
									@yield('alert')
								</div>
    	 						@include('pembayaran.form')
								<div class="form-group">
									<div class="col-md-12">
										<div class="col-md-offset-9 text-right">
											<a href="{{route('pembayaran.index')}}" class="btn btn-warning waves-effect waves-light" > 
												<i class="fa fa-arrow-left m-r-5"></i>
												<span>Batal</span>
											</a>
											{{-- <a href="{{route('pembayaran.index')}}" > 
												<button class="btn btn-warning waves-effect waves-light">
													<i class="fa fa-arrow-left m-r-5"></i>
													<span>Batal</span>
												</button>
											</a> --}}
											<button type="submit" class="btn btn-default waves-effect waves-light">
												<i class="md-autorenew m-r-5"></i>
												<span>Perbarui</span>
											</button>
										</div>
									</div>
								</div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div> <!-- container -->
	</div> <!-- content -->
</div><!-- End Right content here -->
@stop

resources/views/pembayaran/form.blade.php
<div class="form-group">
	<label class="col-md-2 control-label">Tanggal Pembayaran</label>
	<div class="col-md-10">
		<div class="input-group">
			@php
			$tgl_conv = date('Y-m-d', strtotime($pembayaran->tanggal_pembayaran));
                        $tgl_jadi = date('d-m-Y', strtotime($tgl_conv));
			@endphp
			<input type="text" name="tanggal_pembayaran" value="{{$tgl_jadi}}" class="form-control datepickerautoclose" placeholder="tgl-bln-tahun">
			<span class="input-group-addon bg-custom b-0 text-white"><i class="icon-calender"></i></span>
		</div>
	</div>
</div>

<div class="form-group">
	<label class="col-md-2 control-label">Jumlah</label>
	<div class="col-md-10">
		{!! Form::text('jumlah',null,['class'=>'form-control','placeholder'=>"Jumlah",'required'=>'required']) !!}
	</div>
</div>

<div class="form-group">
	<label class="col-md-2 control-label">Bukti Pembayaran</label>
	<div class="col-md-10">
		<input name = "file_resi" type="file" class="filestyle"  value = "{{ $pembayaran->file_resi}}">
		<br>
		<img id="preview" style="margin-bottom: 5px;" src="{{ asset($pembayaran->file_resi) }}" height="100" alt="">
		</input>
	</div>
</div>

<div class="form-group">
    <label class="col-md-2 control-label">Nama Anggota</label>
	<div class="col-md-10">
		<select class="form-control select2" name="anggota_id" id="">
			@foreach ($anggotaPluck as $anggota )
				<option value="{{ $anggota->id}}"
				@if ($anggota->id === $pembayaran->anggota_id)
					selected
				@endif
				>{{ $anggota->nama}} - {{ $anggota->nomor_anggota}} </option>
			@endforeach
		</select>
	</div>
</div>