routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UtamaController@welcome')->name('/');
Route::get('/profil', 'UtamaController@tentang')->name('/profil');
Route::get('/struktur', 'UtamaController@struktur')->name('/struktur');
Route::get('/faq', 'UtamaController@faq')->name('/faq');
Route::get('/blog', 'UtamaController@blog')->name('/blog');
Route::get('/blog-one/{id}', 'UtamaController@blogOne')->name('blog-one');
Route::get('/page_doc', 'UtamaController@page_doc')->name('/page_doc');
Route::get('resource/download_dokumen', ['as' => 'resource.download', 'uses' => 'SessionController@download']);

Route::get('/login', 'SessionController@form')->name('login');
Route::post('/login', 'SessionController@validasi')->name('process_login');
Route::get('/logout', 'SessionController@logout')->name('logout');
Route::get('/registration', 'SessionController@registration')->name('registration');
Route::post('/registration', 'SessionController@registrationStore', ['middleware' => 'web'])->name('process_registration');

Route::group(['prefix' => 'anggota', 'middleware' => 'AnggotaMiddleware'], function () {
    Route::get('/', 'DashboardController@dashboard_anggota')->name('anggota');
    Route::resource('profil_anggota', 'AnggotaProfilController');
    Route::resource('password_anggota', 'UpdatePassword');
    Route::resource('simpanan_anggota', 'AnggotaPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_anggota', 'AnggotaDokumenController');
    Route::get('resource/download_anggota', ['as' => 'anggota.resource.download', 'uses' => 'AnggotaDokumenController@download']);
    Route::resource('belanja_anggota', 'BelanjaAnggotaController');
});

Route::group(['prefix' => 'investor', 'middleware' => 'InvestorMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'InvestorProfilController@getOmset');

    Route::get('/', 'DashboardController@dashboard_investor')->name('investor');
    Route::resource('profil', 'InvestorProfilController');
    Route::resource('password', 'UpdatePassword');
    Route::resource('simpanan', 'InvestorPembayaranController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('investasis', 'InvestorInvestasiController', ['except' => ['show', 'edit', 'update', 'destroy']]);
    Route::resource('dokumen_investor', 'InvestorDokumenController');
    Route::get('resource/download_investor', ['as' => 'investor.resource.download', 'uses' => 'InvestorDokumenController@download']);
    Route::resource('belanja_investor', 'BelanjaInvestorController');
});

Route::group(['prefix' => 'admin', 'middleware' => 'AdminMiddleware'], function () {
    //omset hari ini
    Route::get('api/pos', 'AnggotaController@getOmset');

    Route::get('/', 'DashboardController@dashboard_admin')->name('admin');

    //route laporan unit usaha
    Route::get('/download/{jenis}/{id}', array('as' => 'download', 'uses' => 'LaporanController@download'));
    Route::get('/pdfview/{id}', array('as' => 'pdfview', 'uses' => 'LaporanController@pdfview'));
    Route::get('/iniLaporan', 'LaporanController@iniLaporan')->name('iniLaporan');

    Route::resource('role', 'RoleController', ['except' => [
    'create', 'store', 'destroy',
    ]]);

    Route::resource('user', 'UserController');

    Route::resource('anggota', 'AnggotaController');

    Route::get('anggota/simpanan/{id}', 'AdminAnggotaSimpanan@awal')->name('anggota.simpanan');
    Route::get('anggota/investasi/{id}', 'AdminAnggotaInvestasi@awal')->name('anggota.investasi');

    Route::get('/ubah/anggota/{id}/{status}', 'AnggotaController@status');

    Route::resource('jabatan', 'JabatanController');

    Route::resource('jenis_investasi', 'JenisInvestasiController');

    Route::resource('jenis_pembayaran', 'JenisPembayaranController');

    Route::resource('investasi', 'InvestasiController');
    Route::resource('omset', 'OmsetController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('resource/download', ['as' => 'admin.resource.download', 'uses' => 'DokumenController@download']);

    Route::resource('pembayaran', 'PembayaranController');

    Route::get('/ubah/pembayaran/{id}/{status}', 'PembayaranController@status');

    Route::get('/ubah/investasi/{id}/{status}', 'InvestasiController@status');

    Route::get('/ubah/pengambilan/{id}/{status}', 'PengambilanController@status');

    Route::resource('kepengurusan', 'KepengurusanController');

    Route::resource('penjualan', 'PenjualanController', ['except' => ['show', 'edit', 'destroy']]);

    Route::resource('pengambilan', 'PengambilanController');

    Route::resource('visimisi', 'VisimisiController');

    Route::resource('badanhukum', 'BadanhukumController');

    Route::resource('ketentuan', 'KetentuanController');

    Route::resource('faq', 'FaqController');

    Route::resource('berita', 'BeritaController');

    Route::resource('shu', 'ShuController');

    Route::resource('dewan', 'DewanController');
    Route::resource('belanja', 'BelanjaController');

    Route::get('data-omset','DataOmsetController@dataOmset')->name('data.omset');
    Route::get('data-anggota-tahunan','DataOmsetController@dataAnggotaTahunan')->name('data.anggota.tahunan');
    Route::get('data-keuntungan-tahunan','DataOmsetController@dataKeuntunganTahunan')->name('data.keuntungan.tahunan');

});

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/kirim-sms', function (){
//    $sms = new \App\Helpers\Zenziva();
  //  $sms->send('085652095696','test kirim zenziva sms');
//});

Route::get('/generate-barcode', function () {
    $anggota = new \App\Model\AnggotaModel();
    //use Milon\Barcode\DNS1D;
    $barcode = new \Milon\Barcode\DNS1D();
    $i = 0;
    foreach ($anggota->get() as $row) {
        ++$i;
        //echo '<img src="data:image/png;base64,' . $barcode->getBarcodePNG($row->nomor_anggota, "C128",2,33,array(1,1,1), true) . '" alt="barcode"   />';

        $barcode->setStorPath(storage_path('/app/images/barcode_anggota/'.$row->nama.'_'));
        $img = $barcode->getBarcodePNGPath($row->nomor_anggota, 'C128', 2, 33);
        //echo $barcode->getBarcodePNGPath($row->nomor_anggota, "C128",3,33,array(255,255,0), true);
        // return response($img.'<br>');
        echo $row->nomor_anggota.'<br>';
    }
});

Route::get('/ajax-chart-anggota', 'DashboardController@ajaxChartAnggota')->name('get.ajaxAnggota');
Route::get('/ajax-chart-line-omzet', 'DashboardController@ajaxLineOmzet')->name('get.ajaxLineOmzet');
Route::get('/ajax-change-toko', 'DashboardController@changeToko')->name('get.changeToko');

app/Http/Controllers/JenisPembayaranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\JenisPembayaranModel;
use App\Http\Requests\JenisPembayaranRequest;

class JenisPembayaranController extends Controller
{
    public function index(Request $request)
    {
        $semuaJenisPembayaran= JenisPembayaranModel::Cari($request)->orderBy('created_at', 'DESC')->paginate(5);
        return view('jenis_pembayaran.awal', compact('semuaJenisPembayaran'));
    }

    public function create()
    {
        return view('jenis_pembayaran.tambah');
    }

    public function store(JenisPembayaranRequest $input)
    {
        $jenis_pembayaran= new JenisPembayaranModel();
        $jenis_pembayaran->nama=$input->nama;
        if (!$input->nominal) {
            $jenis_pembayaran->nominal='0';
        } else {
            $jenis_pembayaran->nominal=$input->nominal;
        }
        if (!$input->lama_tempo) {
            $jenis_pembayaran->lama_tempo='0';
        } else {
            $jenis_pembayaran->lama_tempo=$input->lama_tempo;
        }

        $jenis_pembayaran->deskripsi=$input->deskripsi;
        $informasi=$jenis_pembayaran->save() ? 'Berhasil simpan data' : 'Gagal simpan data';
        return redirect()->route('jenis_pembayaran.index')->with(['informasi'=>$informasi]);
    }

    public function edit($id)
    {
        $jenis_pembayaran= JenisPembayaranModel::findOrFail($id);
        return view('jenis_pembayaran.edit')->with(array('jenis_pembayaran'=>$jenis_pembayaran));
    }

    public function update($id, JenisPembayaranRequest $input)
    {
        $jenis_pembayaran= JenisPembayaranModel::findOrFail($id);
        $jenis_pembayaran->nama=$input->nama;
        $jenis_pembayaran->nominal=$input->nominal;
        $jenis_pembayaran->lama_tempo=$input->lama_tempo;
        $jenis_pembayaran->deskripsi=$input->deskripsi;
        $informasi=$jenis_pembayaran->save() ? 'Berhasil update data' : 'Gagal update data';
        return redirect()->route('jenis_pembayaran.index')->with(['informasi'=>$informasi]);
    }

    public function show($id)
    {
        $jenis_pembayaran = JenisPembayaranModel::findOrFail($id);
        return view('jenis_pembayaran.lihat')->with(array('jenis_pembayaran'=>$jenis_pembayaran));
    }

    public function destroy($id)
    {
        $jenis_pembayaran= JenisPembayaranModel::findOrFail($id);
        $informasi=$jenis_pembayaran->delete() ? 'Berhasil hapus data' : 'Gagal hapus data';
        return redirect()->route('jenis_pembayaran.index')->with(['informasi'=>$informasi]);
    }
}

resources/views/jenis_pembayaran/awal.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-box table-responsive">
                            <div class="row">
                                    <div class="col-sm-12">
                                        <div class="btn-group pull-right m-t-15">
                                                <a href="{{route('jenis_pembayaran.create')}}"> <button type="button" class="btn btn-default ">Tambah <span class="m-l-5"><i class=" fa fa-plus fa fa-cog"></i></span></button></a>
                                        </div>
        
                                        <ol class="breadcrumb">
                                            <li>
                                                <a href="#">Admin</a>
                                            </li>
                                            <li class="active">
                                                Jenis Simpanan
                                            </li>
                                        </ol>
                                    </div>
                                </div>

                        <center><h4 class="m-t-0"><b>TABEL JENIS SIMPANAN</b></h4></center>
                        <form action="{{url()->current()}}">
                            <div class="container">
                                <div class="row">
                                    <div class="input-group col-12 col-md-4 pull-right">
                                        {!! Form::text('nama',null,['class'=>'form-control col-md-3','placeholder'=>"Nama"]) !!}          
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn waves-effect waves-light btn-primary">Cari</button>                                        
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    
                        <table id="datatable" class="table table-striped table-bordered">

                        	<!-- Alert -->
							@yield('alert')
						

                            <thead>
                                <tr>
                                        <th width="5%" scope="row">No</th>
                                        <th width="20%" scope="row">Nama</th>
                                        <th width="20%" scope="row">Nominal</th>
                                        <th width="20%" scope="row">Lama Tempo (bulan)</th>
                                        <th width="30%" scope="row">Deskripsi</th>
                                        <th width="10%" scope="row">Action</th>
                                </tr>
                            </thead>


                            <tbody>
                                @php
                                    $no =1;
                                @endphp
                                @foreach($semuaJenisPembayaran as $jenis_pembayaran)
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{$jenis_pembayaran->nama or 'kosong'}}</td>
                                        <td>{{rupiah($jenis_pembayaran->nominal)}}</td>
                                        <td>{{$jenis_pembayaran->lama_tempo or 'kosong'}}</td>
                                        <td>{{$jenis_pembayaran->deskripsi or 'kosong'}}</td>
                                        <td>
                                            {{ Form::open(array('route' => array('jenis_pembayaran.destroy', $jenis_pembayaran->id), 'method' => 'delete')) }}
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-primary dropdown-toggle  waves-effect" data-toggle="dropdown" aria-expanded="false"> Aksi <span class="caret"></span> </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="{{route('jenis_pembayaran.edit', $jenis_pembayaran->id)}}">Ubah</a></li>
                                                        <li><a href="{{route('jenis_pembayaran.show', $jenis_pembayaran->id)}}">Lihat</a></li>
                                                        <button id="btn-action" class="btn btn-white waves-effect waves-light btn-xs" data-toggle="tooltip" data-placement="top" title="Hapus">Hapus</button>
                                                    </ul>
                                                </div>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {!! $semuaJenisPembayaran->appends(Request::except('page'))->render() !!}
                    </div>
                </div>
            </div>
        </div> <!-- container -->

    </div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/jenis_pembayaran/edit.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
	<!-- Start content -->
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-color panel-primary">
						<div class="panel-heading">
							<h3 class="panel-title"> EDIT JENIS SIMPANAN</h3></a>
						</div>
						<div class= "container">
						<!-- Alert -->
							@yield('alert')
						</div>
						<div class="panel-body">
     						{{ Form::model($jenis_pembayaran, array('route' => array('jenis_pembayaran.update', $jenis_pembayaran->id), 'files' => true, 'method' => 'PUT','class'=>'form-horizontal')) }}
    	 						@include('jenis_pembayaran.form')
								 <div class="form-group">
										<div class="col-md-12">
											 <div class="col-md-offset-9 text-right">
													<a href="{{route('jenis_pembayaran.index')}}" class="btn btn-warning waves-effect waves-light" > 
															<i class="fa fa-arrow-left m-r-5"></i>
															<span>Batal</span>
													</a>

											   <button type="submit" class="btn btn-default waves-effect waves-light">
													   <i class="md-autorenew m-r-5"></i>
													   <span>Perbarui</span>
											   </button>

											 </div>
										</div>
								   </div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div> <!-- container -->

	</div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/jenis_pembayaran/form.blade.php
<div class="form-group">
	<label class="col-md-2 control-label">Nama</label>
	<div class="col-md-10">
        {!! Form::text('nama',null,['class'=>'form-control','placeholder'=>"Nama",'required'=>'required']) !!}
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">Nominal</label>
	<div class="col-md-10">
        {!! Form::text('nominal',null,['class'=>'form-control','placeholder'=>"0",'required'=>'required']) !!}
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">Lama Tempo (bulan)</label>
	<div class="col-md-10">
        {!! Form::text('lama_tempo',null,['class'=>'form-control','placeholder'=>"0",'required'=>'required']) !!}
	</div>
</div>
<div class="form-group">
	<label class="col-md-2 control-label">Deskripsi</label>
	<div class="col-md-10">
        {!! Form::textarea('deskripsi',null,['class'=>'form-control','placeholder'=>"Deskripsi",'required'=>'required']) !!}
	</div>
</div>

resources/views/jenis_pembayaran/lihat.blade.php
@extends('master')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
     <!-- Start content -->
     <div class="content">
          <div class="container">
               <div class="row">
                    <div class="col-md-12">
                         <div class="panel panel-color panel-primary">
                              <div class="panel-heading">
                                  <h3 class="panel-title"> DETAIL JENIS SIMPANAN</h3></a>
                              </div>
                              <div class="panel-body">
                                   <table class="table">
                                        <tr>
                                            <td>Nama</td>
                                            <td>:</td>
                                            <td>{{$jenis_pembayaran->nama}}</td>
                                        </tr>
                                        <tr>
                                            <td>Nominal</td>
                                            <td>:</td>
                                            <td>{{$jenis_pembayaran->nominal}}</td>
                                        </tr>
                                        <tr>
                                            <td>Deskripsi</td>
                                            <td>:</td>
                                            <td>{{$jenis_pembayaran->deskripsi}}</td>
                                        </tr>

                                        <tr>
                                            <td class="col-xs-4">Created at</td>
                                            <td class="col-xs-1">:</td>
                                            <td>{{indonesian_date($jenis_pembayaran->created_at)}}</td>
                                        </tr>
                                        <tr>
                                            <td class="col-xs-4">Update at</td>
                                            <td class="col-xs-1">:</td>
                                            <td>{{indonesian_date($jenis_pembayaran->updated_at)}}</td>
                                        </tr>
                                   </table>
                                   <div class="form-group">
                                        <div class="col-md-12">
                                            <div class="col-md-offset-9 text-right">
                                             <a href="{{route('jenis_pembayaran.index')}}">
                                                 <button class="btn btn-warning waves-effect waves-light">
                                                    <i class="fa fa-arrow-left m-r-5"></i><span>Kembali</span>
                                                 </button></a>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                         </div>
                    </div>
               </div>
          </div> <!-- container -->

     </div> <!-- content -->

</div><!-- End Right content here -->
@stop

resources/views/jenis_pembayaran/tambah.blade.php
@extends('master')
@include('errors.alert')
@section('container')
<!-- Start right Content here -->
<div class="content-page">
	<!-- Start content -->
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-color panel-primary">
						<div class="panel-heading">
							<a href="{{route('jenis_pembayaran.index')}}"><h3 class="panel-title"><i class="fa  fa-arrow-left"></i> </h3></a>
						</div>
						 <div class= "container">
							<!-- Alert -->
							@yield('alert')
						 </div>
						<div class="panel-body">
							<center><h4 class="m-t-0"><b>TAMBAH JENIS SIMPANAN</b></h4></center>
							<br>
							{!! Form::open(['route'=>'jenis_pembayaran.store','class'=>'form-horizontal','files'=>true]) !!}
    							@include('jenis_pembayaran.form')
								<div class="form-group">
									<div class="col-md-12">
										<div class="form-group">
											<div class="col-md-12">
												<div class="col-md-offset-9 text-right">
													<button type="reset" class="btn btn-danger waves-effect waves-light">
														<span class="btn-label"><i class="fa fa-repeat"></i>
														</span>Ulangi
													</button>
													<button type="submit" class="btn btn-default waves-effect waves-light">
														<i class="fa fa-save m-r-5"></i>
														<span>Simpan</span>
													</button>
												</div>
											</div>
										</div>
									</div>
								</div>
							{!! Form::close() !!}
						</div>
					</div>
				</div>
			</div>
		</div> <!-- container -->

	</div> <!-- content -->

</div><!-- End Right content here -->
@stop